spring.application.name=CharityProject

# ===============================
# CONFIGURATION POSTGRESQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/charity_db
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA / HIBERNATE
# ===============================
# Permet à Spring Boot de créer automatiquement les tables basées sur tes classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL générées dans la console (pratique pour le débogage)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spécifie le dialecte PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
